-- Custom SQL migration file, put your code below! --
-- No-op in this fork: Neon rejects CREATE EXTENSION pg_search for new projects, which aborts
-- the whole migrate run. Search runs on FTS_SEARCH_PROVIDER=pg_like instead.
