-- Custom SQL migration file, put your code below! --
-- No-op in this fork: bm25 indexes need the pg_search access method, unavailable on Neon.
-- Requires 0090 to stay a no-op; search runs on FTS_SEARCH_PROVIDER=pg_like instead.
